### ISSUE TITLE
Installed Spectrum 0.6.1 Anaconda python 3.5 does not get imported on  Spyder IPython console

### ISSUE THREAD

**Issue by olbakalis** [cokelaer/spectrum#14]
Hello,
I have installed spectrum 0.6.1 on my Anaconda python 3.5 distribution on windows 7.
On the Spyder IPython console it cannot be imported. Would you please help???
Here's the end of the installation output:
....
 File "C:\Users\olb\AppData\Local\Continuum\Anaconda3\lib\site-packages\spectrum-0.6.1-Installed c:\users\olb\appdata\local\continuum\anaconda3\lib\site-packages\spectrum-0.6.1-py3.5-win-amd64.egg
Processing dependencies for spectrum
Finished processing dependencies for spectrum-win-amd64.egg\spectrum

....
Here's the console error:
import spectrum
Traceback (most recent call last):

  File "<ipython-input-1-c2dabc14c746>", line 1, in <module>
    import spectrum

 \__init__.py", line 8, in <module>
    from .mtm import *

  File "C:\Users\olb\AppData\Local\Continuum\Anaconda3\lib\site-packages\spectrum-0.6.1-py3.5-win-amd64.egg\spectrum\mtm.py", line 53, in <module>
    mtspeclib = ctypes.cdll.LoadLibrary(pj(p, lib_name))

  File "C:\Users\olb\AppData\Local\Continuum\Anaconda3\lib\ctypes\__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)

  File "C:\Users\olb\AppData\Local\Continuum\Anaconda3\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)

OSError: [WinError 126] The specified module could not be found

**Comment by olbakalis** [comment]
Fixed: 
Bug in code mtm.py:
under: if platform.system() == 'Windows':
line 46 was: lib_name = 'mydpss.pyd'
This file does not exist. mydpss.py does and has the name of the existing library:
lib_name = 'mydpss.cp35-win_amd64.pyd'
